# Generated by Django 4.1.7 on 2023-03-03 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(default='no nicknames known', max_length=100)),
                ('origin', models.CharField(default='unknown origin', max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('staff_level', models.CharField(choices=[('captain', 'CAPTAIN'), ('xo', 'XO'), ('unassigned', 'UNASSIGNED')], default='unassigned', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedinaDock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('armament', models.TextField(max_length=300)),
                ('engine_type', models.TextField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='MyShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=60)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='flottille.crew')),
                ('medina_dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medina_dock', to='flottille.medinadock')),
                ('spaceship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaceship', to='flottille.spaceship')),
                ('xo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xo', to='flottille.crew')),
            ],
        ),
    ]
