# Generated by Django 4.1.7 on 2023-03-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottille', '0002_spaceship_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceship',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
