# Generated by Django 4.1.7 on 2023-03-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottille', '0004_alter_spaceship_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='staff_level',
            field=models.CharField(choices=[('admiral', 'ADMIRAL'), ('captain', 'CAPTAIN'), ('xo', 'XO'), ('unassigned', 'UNASSIGNED')], default='unassigned', max_length=20),
        ),
    ]
