# Generated by Django 4.1.7 on 2023-03-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flottille', '0005_alter_crew_staff_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myship',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_captain', to='flottille.crew'),
        ),
        migrations.AlterField(
            model_name='myship',
            name='medina_dock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_dock', to='flottille.medinadock'),
        ),
        migrations.AlterField(
            model_name='myship',
            name='spaceship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_spaceship', to='flottille.spaceship'),
        ),
        migrations.AlterField(
            model_name='myship',
            name='xo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_xo', to='flottille.crew'),
        ),
    ]
