# Generated by Django 4.1.7 on 2023-03-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flottille', '0006_alter_myship_captain_alter_myship_medina_dock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='staff_level',
            field=models.CharField(choices=[('unassigned', 'UNASSIGNED'), ('admiral', 'ADMIRAL'), ('captain', 'CAPTAIN'), ('XO', 'XO')], default='unassigned', max_length=20),
        ),
    ]
